create database retail_project;

use retail_project
go

select * from SampleSuperstore

select AVG(sales) as avg_sales from SampleSuperstore

--1. •	Question: Calculate the total sales for each region.

select Region, sum(sales) as total_sales from SampleSuperstore
group by Region

--2. •	Question: Calculate the total profit generated by each customer segment.

select Segment, sum(cast(Profit as float)) as total_profit from SampleSuperstore
group by Segment

--3. •	Question: Identify the top 5 cities with the highest total profit.

select top 5 city, sum(cast(Profit as float)) as total_profit from SampleSuperstore
group by city
order by total_profit desc

--4. •	Question: Calculate total sales for each category and its corresponding sub-categories.

select category, sub_category, sum(sales) as total_sales from SampleSuperstore
group by category, sub_category

--5. •	Question: Find the average discount offered in each region.

select region, AVG(cast (Discount as float)) as Avg_Discount from SampleSuperstore
group by region

select distinct region, avg(cast (Discount as float)) over(partition by region order by region) as Avg_Discount from SampleSuperstore

--6.•	Question: Calculate the total sales for each ship mode.

select Ship_Mode, sum(Sales) as total_sales from SampleSuperstore
group by Ship_Mode

--7.•	Question: Find out the total quantity of products sold in each state.

select "State", sum(cast (Quantity as int)) as total_quantity from SampleSuperstore
group by "State"

--8.•	Question: Identify the most profitable customer segment for each region.

--select sum(cast(Profit as float)) over(partition by Region order by Profit desc) as total_profit from SampleSuperstore

select *, max(total_profit) as max_profit from
(select segment, region, sum(cast(Profit as float)) as total_profit from SampleSuperstore
group by segment, region) k
group by k.segment, k.region

select max(total_profit) from
(select segment, region, sum(cast(Profit as float)) as total_profit from SampleSuperstore
group by segment, region) k
where region in ('East','South','West','Central')

select segment, region, max(cast(Profit as float)) as total_profit from SampleSuperstore
group by segment, region

--9. •	Question: Find the top 5 product categories with the highest sales.

select top 5 category, sum(sales) as total_sales from SampleSuperstore
group by category
order by total_sales desc

select distinct category from SampleSuperstore

--10. •	Question: Calculate the total sales and total profit for each country.

select country, sum(sales) as total_sales, sum(cast(Profit as float)) as total_profit from SampleSuperstore
group by country

select distinct country from SampleSuperstore

--11. •	Question: Calculate the average profit for each product category.

select category, avg(cast (profit as float)) as avg_profit from SampleSuperstore
group by category

--12. •	Question: Analyze the relationship between discount and profit by calculating total profit for discounted and non-discounted sales.

select Discount_Applicable, sum(cast(profit as float)) as total_profit from
(select *,
         case when cast(discount as float) = 0 then 'NoDiscount'
			  when cast(discount as float) != 0 then 'Discount'
		 end as 'Discount_Applicable'
from SampleSuperstore) k
group by Discount_Applicable

select sum(cast(profit as float)) as total_profit from SampleSuperstore

--13.•	Question: Calculate the total sales for each postal code.

select postal_code, sum(sales) as total_sales from SampleSuperstore
group by postal_code

--14. •	Question: Find the orders with a discount greater than 20% and a profit higher than $100.

select * from SampleSuperstore
where discount > 0.2 and cast(profit as float) > 100

select * from SampleSuperstore

--15. •	Question: Identify the most profitable state for each region.

select "state", region, sum(cast(profit as float)) as total_profit from SampleSuperstore
group by "state", region

--16. •	Question: Identify the top 3 sub-categories with the highest quantity sold in each product category.

select top 3 category, sub_category, sum(cast(quantity as int)) as total_quantity from SampleSuperstore
group by category, sub_category
order by total_quantity desc

--17.•	Question: Calculate the total sales and profit for each state.

select "state", sum(sales) as total_sales, sum(cast(profit as float)) as total_profit
from SampleSuperstore
group by "state"

--18. •	Question: Calculate the average discount given for each ship mode.

select ship_mode, avg(cast(discount as float)) as avg_discount from SampleSuperstore
group by ship_mode

--19. •	Question: Calculate the profit margin for each product category. (Profit margin = Profit / Sales)

select category, sum(cast(profit as float))/sum(sales) as profit_margin from SampleSuperstore
group by category

select * from SampleSuperstore

--20. •	Question: Find the total quantity of products sold in each region.

select region, sum(cast(quantity as int)) as total_quantity from SampleSuperstore
group by region